spring:
  datasource:
    url: jdbc:mysql://180.231.212.212:3306/best_pie?serverTimezone=Asia/Seoul
    username: root
    password: Sysadmin1!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace #??? ?? 3.x, hibernate6